/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.input.ScrollEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.util.Duration;

public class App extends Application {
    private Timeline timeline;
    private int totalSeconds;

    @Override
    public void start(Stage primaryStage) {
        ComboBox<Integer> hourBox = createComboBox(0, 23);
        ComboBox<Integer> minuteBox = createComboBox(0, 59);
        ComboBox<Integer> secondBox = createComboBox(0, 59);
        BorderPane pane = new BorderPane();

        HBox layout = new HBox(10, hourBox, minuteBox, secondBox);
        layout.setPadding(new Insets(20));
        layout.setAlignment(Pos.CENTER);
        pane.setCenter(layout);
        Button startButton = new Button("Start");
        HBox buttons = new HBox(startButton);
        buttons.setPadding(new Insets(20));
        buttons.setAlignment(Pos.CENTER);
        pane.setBottom(buttons);
        startButton.setOnAction((e)->{
            int hours = hourBox.getValue();
            int minutes = minuteBox.getValue();
            int seconds = secondBox.getValue();
            startCountdown(pane, hours, minutes, seconds);
        });
        Scene scene = new Scene(pane, 300, 200);
        primaryStage.setTitle("Samsung-like Timer");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private ComboBox<Integer> createComboBox(int start, int end) {
        ComboBox<Integer> comboBox = new ComboBox<>();
        for (int i = start; i <= end; i++) {
            comboBox.getItems().add(i);
        }
        comboBox.setValue(start);
        comboBox.setOnScroll((ScrollEvent event) -> {
            int currentIndex = comboBox.getSelectionModel().getSelectedIndex();
            if (event.getDeltaY() > 0) {
                if (currentIndex < comboBox.getItems().size() - 1) {
                    comboBox.getSelectionModel().selectNext();
                }
            } else {
                if (currentIndex > 0) {
                    comboBox.getSelectionModel().selectPrevious();
                }
            }
        });

        return comboBox;
    }
    private void startCountdown(BorderPane pane, int hours, int minutes, int seconds) {
        totalSeconds = hours * 3600 + minutes * 60 + seconds; // Convert time to total seconds

        timeline = new Timeline(new KeyFrame(Duration.seconds(1), event -> {
            totalSeconds--;

            int remainingHours = totalSeconds / 3600;
            int remainingMinutes = (totalSeconds % 3600) / 60;
            int remainingSeconds = totalSeconds % 60;

            String formattedTime = String.format("%02d:%02d:%02d", remainingHours, remainingMinutes, remainingSeconds);
            Platform.runLater(() -> pane.setCenter(new Text(formattedTime)));
            if (totalSeconds <= 0) {
                timeline.stop();
                Platform.runLater(() -> pane.setCenter(new Text("Time's up!")));
                new Thread(new BackgroundMusic()).start();
            }
        }));
        timeline.setCycleCount(Timeline.INDEFINITE);
        timeline.play();
    }
}
